version: '3'
services:
  socket:
      image: tecnativa/docker-socker-proxy
      privileged: true
      ports:
        - "4001"
        - "2375:2375"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  script:
    build: ./script
    image: rts_script:v0.1
    depends_on:
      - mqtt
    volumes:
      - ./script:/script

  site:
    build: ./site
    image: rts_site:v0.1
    ports:
      - "8000:5000"
    depends_on:
      - db
    volumes:
      - ./site:/site

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883"
      - "9001:9001"

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
