apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - args:
        - mongod
        - --smallfiles
        - --logpath=/dev/null
        env:
        - name: MONGO_DATA_DIR
          value: /usr/data/db
        - name: MONGO_LOG_DIR
          value: /dev/null
        image: mongo:latest
        name: db
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
